const color = require('colors')
const readlineSync = require('readline-sync')
let numerouno = readlineSync.question('favor de darme el numero 1: ')
let numerodos = readlineSync.question('favor de darme el  numero 2:')
let resultado = parseInt(numerouno) + parseInt(numerodos)
console.log(`EL PRIMER NUMERO ES...\n${color.blue('numero 1:')} ${numerouno}\n`)
console.log(`EL SEGUNDO NUMERO ES... \n${color.yellow('numero 2:')} ${numerodos}\n`)
console.log(`EL RESULTADO DE LA SUMA ES: \n${color.green('resultado:')} ${resultado}\n`)
readlineSync('preciona cualquier tecla para terminar el programa')
